config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets, except: [ :edit ]
  post "/tickets/:id/comments", to: "comments#create", as: "new_comments"

  root "pages#home"
  get "about", to: "pages#about"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket, dependent: :destroy
  belongs_to :user
  validates :user, presence: true
  validates :ticket, presence: true
  validates :message, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user
  belongs_to :ticket_informant
  has_many :comments

  validates :ticket_informant, presence: true
  validates :name, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :status, presence: true
  validates_associated :ticket_informant

  scope :open, -> { where(status: 1) }
  scope :with_response, -> { where(status: 2) }
  scope :hold, -> { where(status: 3) }
  scope :canceled, -> { where(status: 4) }
  scope :completed, -> { where(status: 5) }
  scope :recent, -> { order("created_at DESC").limit(5) }
  scope :updated, -> { order("updated_at DESC").limit(5) }
end

app/models/ticket_informant.rb
class TicketInformant < ActiveRecord::Base
  has_one :ticket
  validates :username, presence: true
  validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [ :create ]

  def create
    @comment = @ticket.comments.create comment_params
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @ticket
  end

  private

    def set_ticket
      @ticket = TicketsResources.get_ticket(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [ :about ]

  def home
    @recent = TicketsResources.recent
    @updated = TicketsResources.updated
  end
  
  def about
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [ :new, :create, :show ]
  before_action :set_tickets_resources, only: [:show, :edit, :update, :destroy]
  
  def index
    @data = TicketsResources.tickets
    render :index
  end
  
  def new
    @ticket_form = TicketForm.new
  end
  
  def show
    @comment = Comment.new
  end
  
  def create
    @ticket_form = TicketForm.new(ticket_params)
    if @ticket_form.valid?
      @tickets_resources = TicketsResources.new(@ticket_form)
      redirect_to @tickets_resources.ticket if @tickets_resources.save
    else
      render :new
    end
  end
  
  def update
    @tickets_resources.update(ticket_params, current_user.id)
    redirect_to tickets_path
  end
  
  def destroy
    @tickets_resources.destroy
    redirect_to tickets_path
  end
  
  private
  
  def ticket_params
    params.require(:ticket_form).permit(:title, :description, :username, :email, :status)
  end
  
  def set_tickets_resources
    @tickets_resources = TicketsResources.new
    @tickets_resources.setup_resource(params[:id])
    @ticket = @tickets_resources.ticket
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_table
    render partial: 'comments_table'
  end

  def new_comment_form
    if !current_user.nil? && current_user.tickets.include?(@ticket)
      render partial: 'comment_form'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def header_link path, path_name
    classes = "active" if request.env["PATH_INFO"] == path
    render inline: "<li class=#{classes}>#{link_to path_name, path}</li>"
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  TICKETS_STATUS_LIST = [
      [ "Waiting for Stuff Response", 1 ],
      [ "Waiting for Customer", 2 ],
      [ "On Hold", 3 ],
      [ "Canceled", 4 ],
      [ "Completed", 5 ]
    ]
  
  def rand_str
    (0...3).map { ('A'..'Z').to_a[rand(26)] }.join
  end
  
  def rand_hex
    SecureRandom.hex(1)
  end
  
  def tickets_panel(tickets, scope_name)
    @tickets = tickets
    @scope = scope_name
    render "tickets_panel", tickets: @tickets, scope: @scope
  end
  
  def update_ticket_status_path(id, status)
    {
      controller: "tickets",
      action: "update",
      id: id,
      ticket_form: {
        status: status
      }
    }
  end
  
  def ticket_status_label
    status = TICKETS_STATUS_LIST[@ticket.status - 1][0]
    render inline: "<span class='label #{label_class_by_status}'>#{status}</span>"
  end
  
  def label_class_by_status
    case @ticket.status
    when 1, 2
      "label-info"
    when 3
      "label-default"
    when 4
      "label-danger"
    else
      "label-success"
    end
  end
  
  def user_actions
    if !current_user.nil?
      render 'action_block', ticket: @ticket
    end
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta(name="viewport" content="width=device-width, initia-scale=1.0, user-scalable=1, minimum-scale=1.0, minimum-scale=1.0, maximum-scale=1.0")
    %meta(name="theme-color" content="#e7e7e7")
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Ticket App
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            = header_link tickets_path, "Tickets"
            = header_link new_ticket_path, "Create Ticket"
          %ul.nav.navbar-nav.navbar-right
            - if current_user.nil?
              = header_link new_user_registration_path, "Sign Up"
              = header_link new_user_session_path, "Sign In"
            - else
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = current_user && current_user.email
                  %span.caret
                %ul.dropdown-menu
                  = header_link tickets_path, 'Tickets'
                  = header_link "#", 'My Ticket'
                  = header_link "#", 'My Comments'
                  %li.divider{:role => "separator"}
                  = header_link edit_user_registration_path, 'Profile Settings'
                  %li
                    = link_to "Sign Out", destroy_user_session_path, method: :delete
    .container
      = yield

app/views/pages/about.haml
.col-md-8.col-md-offset-2.col-xs-12
  %h1 This is Ticket Test Application
  %p created by N.Sheremet

app/views/pages/home.haml
.col-md-8.col-md-offset-2.col-xs-12
  %h2 Last added tickets
  %br
  .panel.panel-default
    .panel-heading
      %h4 Recent Tickets
    %table.table.table-hover
      - @recent.each do |item|
        %tr
          %td
            = item.name
          %td
            = item.title
          %td.actions
            = link_to 'Show', item, class: 'btn btn-xs btn-info'

  .panel.panel-default
    .panel-heading
      %h4 Last Updated
    %table.table.table-hover
      - @updated.each do |item|
        %tr
          %td
            = item.name
          %td
            = item.title
          %td.actions
            = link_to 'Show', item, class: 'btn btn-xs btn-info'

app/views/tickets/_action_block.haml
.panel.panel-warning
  .panel-heading
    %h4 Ticket Actions
  .panel-body
    - if ticket.user.nil?
      %h5 You can Assign/Unassign ticket to your account
      = button_to "Assign", update_ticket_status_path(ticket.slug, 2), method: :patch, class: 'btn btn-success'
    %h5 You can check as Complete status
    = button_to "Complete", update_ticket_status_path(ticket.slug, 5), method: :patch, class: 'btn btn-info'
    %h5 You can check as Canceled status
    = button_to "Canceled", update_ticket_status_path(ticket.slug, 4), method: :patch, class: 'btn btn-danger'
    %h5 You can check as On Hold status
    = button_to "Hold", update_ticket_status_path(ticket.slug, 3), method: :patch, class: 'btn btn-default'
  .panel-footer  
    .alert.alert-danger
      %h5 You can `Delete` this ticket
      = button_to "Delete", ticket_path(ticket.slug), method: :delete, class: 'btn btn-danger'

app/views/tickets/_comment_form.haml
= form_for @comment, url: new_comments_path(@ticket.slug) do |f|
  .form-group
    = f.text_area :message, class: 'form-control', placeholder: 'Type comment here..'
  .form-group
    = f.submit 'Add Comment', class: 'btn btn-success'

app/views/tickets/_comments_table.haml
%table.table.table-hover
  - if !@ticket.comments.blank?
    - @ticket.comments.each do |item|
      %tr
        %td= item.message
        %td= item.created_at
  - else
    %h5.text-center No comments yet!

app/views/tickets/_tickets_panel.haml
- if !tickets.nil? && tickets.any?
  .panel.panel-default
    .panel-heading 
      %h5 
        = scope
    %table.table.table-hover.tickets-table
      %tbody
        - tickets.each do |item|
          %tr
            %td
              %small= item.name
            %td
              %small= item.title
            %td.actions= link_to 'Show', item, class: 'btn btn-xs btn-info'
            - if item.user.nil?
              %td.actions= button_to "Assign", update_ticket_status_path(item.slug, 2), method: :patch, class: 'btn btn-xs btn-success'

app/views/tickets/index.haml
.col-md-8.col-md-offset-2.col-xs-12
  = tickets_panel @data[:open], 'Open'
  = tickets_panel @data[:with_response], 'With Response'
  = tickets_panel @data[:hold], 'Hold'
  = tickets_panel @data[:canceled], 'Canceled'
  = tickets_panel @data[:completed], 'Completed'

app/views/tickets/new.haml
.col-md-8.col-md-offset-2.col-xs-12
  .alert.alert-info
    Hi friend, here you can create a ticket, just type you `name` , `email` and information about your problem!
  = form_for @ticket_form, url: tickets_path do |f|
    - if @ticket_form.errors.any?
      .alert.alert-danger
        %ul
          - @ticket_form.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.text_field :title, class: 'form-control', placeholder: 'Ticket title'
    .form-group
      = f.email_field :email, class: 'form-control', placeholder: 'Email'
    .form-group
      = f.text_field :username, class: 'form-control', placeholder: 'User name'
    .form-group
      = f.text_area :description, class: 'form-control', placeholder: 'Enter here ticket description'
    .form-group
      = f.submit 'Create ticket', class: 'btn btn-info'

app/views/tickets/show.haml
.col-md-8.col-md-offset-2.col-xs-12.tickets_show
  .col-md-8.col-xs-12
    .panel.panel-info
      .panel-heading
        %h5= @ticket.name
        = ticket_status_label
      .panel-body
        %h4
          = @ticket.title
        %p
          = @ticket.description
    .panel.panel-info
      .panel-heading
        %h5 Comments
      .panel-body
        = new_comment_form
      = comments_table
  .col-md-4.col-xs-12
    = user_actions